import {
	enterAddress,
	enterElevator,
	enterEmail,
	enterFloor,
	enterName,
	enterParking,
	enterPrice,
	selectAmenity,
	selectParkingType,
} from "../redux/rootSlice";

import { emailPattern, namePattern, floorPattern } from "./inputValidations";

export const steps = [
	{
		path: "datos-cliente",
		component: "input-field",
		type: "text",
		pattern: namePattern,
		required: true,
		order: 1,
		description: "Nombre completo",
		name: "userName",
		label: "Ingresa nombre(s) y apellidos",
		placeholder: "Ruth Rivera Marín",
		action: enterName,
		panelName: "Nombre",
		nextPath: "email",
		prevPath: "",
	},
	{
		path: "email",
		component: "input-field",
		type: "email",
		pattern: emailPattern,
		required: true,
		order: 2,
		description: "Correo electrónico",
		name: "email",
		label: "Ingresa un correo válido",
		placeholder: "ruth_rivera@gmail.com",
		action: enterEmail,
		panelName: "Correo",
		nextPath: "direccion",
		prevPath: "datos-cliente",
	},
	{
		path: "direccion",
		component: "input-field",
		type: "text",
		required: true,
		order: 3,
		description: "Dirección del inmueble",
		name: "address",
		placeholder:
			"Av. Insurgentes Sur 105, Roma Sur, Cuauhtémoc, 06600 Ciudad de México, CDMX",
		label: "Ingresa la dirección completa del apartamento",
		action: enterAddress,
		panelName: "Dirección",
		nextPath: "piso",
		prevPath: "email",
	},
	{
		path: "piso",
		component: "input-field",
		type: "number",
		max: floorPattern,
		required: true,
		order: 4,
		description: "Piso del apartamento",
		name: "floor",
		label: "Ingresa el número de piso del apartamento",
		placeholder: "4",
		action: enterFloor,
		panelName: "Piso",
		nextPath: "amenidades",
		prevPath: "direccion",
	},
	{
		path: "amenidades",
		component: "radio",
		required: true,
		order: 5,
		description:
			"Escoge una de las siguientes opciones con las que cuenta tu apartamento",
		name: "amenity",
		label: "Amenidades",
		action: selectAmenity,
		panelName: "Amenidades",
		options: ["Zona BBQ", "Salón comunal", "Parque de juegos"],
		nextPath: "estacionamiento",
		prevPath: "piso",
	},
	{
		path: "estacionamiento",
		component: "radio",
		required: true,
		order: 6,
		description: "¿El inmueble tiene estacionamiento?",
		name: "hasParking",
		label: "Elige alguna de las opciones",
		action: enterParking,
		panelName: "Estacionamiento",
		options: ["Sí", "No"],
		subOptions: {
			description: "¿El estacionamiento está cubierto?",
			name: "parkingType",
			label: "Elige alguna de las opciones",
			action: selectParkingType,
			panelName: "Tipo de estacionamiento",
			options: ["Sí", "No"],
		},
		nextPath: "precio-inmueble",
		prevPath: "amenidades",
	},
	{
		path: "precio-inmueble",
		component: "input-field",
		type: "number",
		required: true,
		order: 7,
		description: "Precio del apartamento",
		name: "price",
		label: "Ingresa el precio de venta del apartamento en pesos mexicanos",
		placeholder: "$1,000,000",
		action: enterPrice,
		panelName: "Precio",
		nextPath: "elevador",
		prevPath: "estacionamiento",
	},
	{
		path: "elevador",
		component: "radio",
		required: true,
		order: 8,
		description: "¿El inmueble cuenta con elevador?",
		name: "hasElevator",
		label: "Selecciona una opción",
		action: enterElevator,
		panelName: "Elevador",
		options: ["Sí", "No"],
		nextPath: "resultados",
		prevPath: "precio-inmueble",
	},
];
